# Generated by Django 5.0.4 on 2024-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='prodpic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
