# Generated by Django 5.0.4 on 2024-05-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=500)),
                ('msgdate', models.CharField(max_length=30)),
                ('expdate', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('productpic', models.FileField(upload_to='')),
                ('avail', models.CharField(max_length=5)),
            ],
        ),
    ]
