# Generated by Django 5.0.4 on 2024-05-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='msgdate',
            new_name='mfgdate',
        ),
    ]
